### ISSUE TITLE
Fatal Error - Lists are not supported by getDocument() yet

### ISSUE THREAD

**Issue by danjaywing** [jkphl/micrometa#12]
'Lists are not supported by getDocument() yet'

The above fatal error observed when attempting to parse data from the following url: 

'http://www.bbc.co.uk/news/business-38966165'

Any ideas?

**Comment by jkphl** [comment]
@danjaywing Looks like this is an upstream issue / todo in the [JsonLD processor](https://github.com/lanthaler/JsonLD) used by micrometa rather than a bug in micrometa itself. The exception is thrown [here](https://github.com/lanthaler/JsonLD/blob/master/Processor.php#L288). Would you mind [opening an issue](https://github.com/lanthaler/JsonLD/issues/new) over at that repository?
