### ISSUE TITLE
Installation with composer

### ISSUE THREAD

**Issue by alexschwarz89** [jkphl/micrometa#2]
Something is weird about the composer/autoloading integration. Instead of installing the dependencies into my vendor folder, it adds a new vendor folder and then is not compatible with composer's autoload. 

However, if I remove the lines searching and including the autoload in Micrometa.php, it works fine with including the class.

(Enviroment: OS X 10.10.3, PHP 5.5.15, Composer version 1.0-dev)

**Comment by jkphl** [comment]
Hey @alexschwarz89,

first of all sorry for not being more responsive!

That sounds really strange — and I have no idea what I should do about it as there's nothing special about the use of composer here. Could you please elaborate on

> Instead of installing the dependencies into my vendor folder, it adds a new vendor folder and then is not compatible with composer's autoload.

What's the name / path of the "new `vendor` folder" that is created, and where would you expect it else?

Cheers, Joschi

**Comment by jkphl** [comment]
Any updates on this? Maybe things changed with [v0.3.3](https://github.com/jkphl/micrometa/releases/tag/v0.3.3) as I added a PSR-4 autoloader entry to `composer.json`‽

**Comment by KennyDurand** [comment]
Hi @jkphl,

I encountered the same problem:
1. `composer require jkphl/microdata` installs your package and all its dependencies.
2. When I try to use Microdata classes, I get the error message anyway:

    Please follow the instructions to install the additional libraries that micrometa is depending on.

3. I [forked your repo](https://github.com/KennyDurand/micrometa) and removed the part where `vendor/autoload` is checked, and then it works.

I think you should consider checking in a different way if your dependencies are present (or not checking at all, maybe, since Composer takes care of everything?). I'm not completely sure what is the best way though, since I'm not very good at Composer.

**Comment by jkphl** [comment]
@KennyDurand Thanks for reporting this! I'm currently completely overloaded and not sure when I will have time to look into this. Please bear with me — thanks!

**Comment by KennyDurand** [comment]
@jkphl No problem sir, I got it working on my side using my fork, so no pressure! Good luck :)
