### ISSUE TITLE
JSON LD with `sameas` throws `InvalidArgumentException`

### ISSUE THREAD

**Issue by dabernathy89** [jkphl/micrometa#21]
I'm honestly not sure if this is an issue with the underlying JSON LD Parser or not. But an exception is thrown for metadata that includes the `sameAs` property. Testing with some example code:

```
{
"@context": "http://schema.org",
"@type": "Website",
"name": "Example Website",
"url": "https://example.com",
"sameAs": [
  "https://facebook.com/Example",
  "https://twitter.com/Example"
]
}
```

Which appears to be valid:

https://www.dropbox.com/s/sfcs4ifc9lj8izr/Screenshot%202017-06-19%2010.34.02.png?dl=0

Parsing this snippet results in an `InvalidArgumentException` with the message `Empty type list is not allowed`. After digging a little bit this appears to be due to the existence of the `sameAs` property.

**Comment by jkphl** [comment]
@dabernathy89 It is possible that this is already fixed in the master branch, see https://github.com/jkphl/micrometa/commit/c44150d94f7390c256e7899188c889ee670a9e8f. There's another problem with certain JSON-LD constellations though which I'm currently working on before I can release this. Please bear with me.

**Comment by dabernathy89** [comment]
Indeed it does work on the master branch. Thanks! Next time i'll check that first!

**Comment by jkphl** [comment]
Not your fault, it's unreleased so you couldn't know! ;)
