### ISSUE TITLE
Poorly coded Microdata attributes

### ISSUE THREAD

**Issue by ala747** [jkphl/micrometa#24]
Hi!

Is there any way to deal with poorly coded Microdata attributes which specifically mess up with the Vocabulary URI?

For example, fetching "https://www.belibe.it/zoccoli-professionali-dian-eva.html" while looking for Microdata I got a "BreadcrumbList" with some "ListItem" inside (yes, it's ok) but I also got a "https://schema.org/Product" (not a "Product") with "//schema.org/Offer" inside "offer" property. It's clear that they are not using just one Vocabulary URI but three: "http://schema.org", "https://schema.org" and "//schema.org".

How could I get all three as just one?

Thanks!

**Comment by jkphl** [comment]
Unfortunately, I think I have to say: By design, you can't. Per specification, item types [may only contain absolute URLs](https://www.w3.org/TR/microdata/#items) which are defined by [RFC3986](https://tools.ietf.org/html/rfc3986#section-4.3) and seem to require a scheme part. Thus, `//schema.org` is not a valid absolute URL and no valid item type either. Similarly, the vocabulary identifier `https://schema.org` is simply wrong — regardless whether it incidentially dereferences to `http://schema.org` or not. Thinking of the vocabulary identifiers as a namespace, `https://schema.org` and `http://schema.org` are fundamentally different and may not be resolved to one and the same thing. In fact, the specification says:

> User agents must not automatically dereference unknown URLs given as item types and property names. These URLs are a priori opaque identifiers.

I don't think it can (and should) be micrometa's job to compensate for source code errors like that. You'd have to roll your own sanitizing layer to get this working.

**Comment by ala747** [comment]
Fair enough :)

I'll fetch and sanitize the input before use Micrometa.

Thank you very much for your attention!

**Comment by rvanlaak** [comment]
Get the argumentation here on the namespace being different. This is something we can work around as the library's implementation is flexible enough for that.

A consequence is that calling `item->toObject` will lead to an invalid `type`:

![image](https://user-images.githubusercontent.com/2707563/67552732-eaf2ea80-f70b-11e9-9916-c7d569af109b.png)

Can the behavior on `toObject` be seen as bug? The IRI `http://schema.org/https://schema.org/WebPage` then also should be seen as invalid.

What about adding several helpers for sanitizing / handling http & https on the profile equally?
