### ISSUE TITLE
related feed URL incorrect

### ISSUE THREAD

**Issue by cweiske** [jkphl/micrometa#9]
https://cweiske.de/tagebuch/feed/index.htm has a related feed URL, but micrometa does not return the correct one.

micrometa: http://cweiske.de/feed/
correct: http://cweiske.de/tagebuch/feed/

Maybe some issue with base href parsing.

URL: https://cweiske.de/tagebuch/feed/index.htm
Base href: `<base href="../"/>`
Feed URL: `<link rel="alternate" type="application/atom+xml" title="Christians Tagebuch" href="feed/" />`

**Comment by cweiske** [comment]
The URLs of all h-entries are incorrect, too.

**Comment by jkphl** [comment]
@cweiske Thanks for reporting, Christian. I will try to look into this asap!

**Comment by jkphl** [comment]
@cweiske I could improve relative base URL handling in *micrometa* a little, but the real problem seems to lie in [php-mf2](https://github.com/indieweb/php-mf2) rather than in *micrometa*. According to the inline comments there [you must be high ;)](https://github.com/indieweb/php-mf2/blob/master/Mf2/Parser.php#L307) and the `resolveUrl()` function [doesn't return the result you expect](https://github.com/indieweb/php-mf2/blob/master/Mf2/Parser.php#L1358). Just do a simple call to to `resolveUrl('https://cweiske.de/tagebuch/feed/index.htm ', '../')` and see yourself...

Would you mind openig an issue with your case over there?

**Comment by cweiske** [comment]
Strangely, http://pin13.net/mf2/?url=https%3A%2F%2Fcweiske.de%2Ftagebuch%2Ffeed%2Findex.htm does list the correct URLs - and it uses php-mf2, too.

**Comment by jkphl** [comment]
@cweiske Hmm. Then there's one explanation: The resolution of the alternate URL in pin13 doesn't rely on the (false) determination of the base URL by php-mf2. I will again look into that and see if I could do the same for *micrometa*. Thanks again.

**Comment by cweiske** [comment]
No, php-mf2 should be fixed.

**Comment by jkphl** [comment]
@cweiske In any case. But still, just in case that php-mf2 isn't responsible for alternate URL resolution anyway, *micrometa* needs to be fixed as well (just as Aaron probably did with pin13).

**Comment by cweiske** [comment]
`resolveUrl()` does seem to be correct:

```
$fullbase = mf2\resolveUrl('https://cweiske.de/tagebuch/feed/index.htm', '../');
$feed = mf2\resolveUrl($fullbase, 'feed/');
var_dump($fullbase, $feed);
```
gives:
```
string(28) "https://cweiske.de/tagebuch/"
string(33) "https://cweiske.de/tagebuch/feed/"
```

This is correct.

Or did you want to say that php-mf2 ignores the base url tag?

**Comment by cweiske** [comment]
No, php-mf2 is correct.

**Comment by jkphl** [comment]
@cweiske That is super strange! I did the very same test yesterday, and calling `resolveUrl` definitely screwed the URL. I will look into that again later today. Thanks for examining!

**Comment by jkphl** [comment]
@cweiske Hmm ... must have overseen this yesterday, but my changes yesterday seem to have fixed this issue. Pushing out a bugfix release now ... Thanks again!
